# Number Guessing Game
import random
import time

def number_guessing_game():

    """
    A number guessing game in which the user has to guess the number generated by the program
    between 1-100. The user can decide the number of tries themselves or can go with the
    predefined number of tries, which is 10 tries to guess the number.

    The program ensures the input validation so that the inputs are within the range.
    Displays hints and previous guesses made by the user.
    User can quit at any point of the game by typing 'Q' or 'q'.
    User can choose to play again after completing a game.
    """

    while True:
        target_number = random.randint(1, 100)
        prev_guess = []

        print("Would you like to set the number of tries or go with the predefined number of tries?")
        ask_for_tries = input("Write (yes) for user-defined / write (no) for system defined. What's your choice? ").strip().lower()
        if ask_for_tries in ["yes", "y"]:
            try:
                print("Keep the number of tries as low as possible for more fun!!")
                tries = int(input("Challenge yourself with your own number of tries: ").strip())
                if tries <= 0 or tries > 15:
                    print("Tries must be between 0 and 15, else it won't be fun!")
                    continue
            except ValueError:
                print("Enter a valid number!!")
                continue
        elif ask_for_tries in ["no", "n"]:
            tries = 10
        else:
            print("Invalid input! Please enter 'yes' or 'no' as input.")
            continue

        while tries > 0:
            user_input = input("Enter your guess (1-100) or press q/Q to exit the game: ").strip()

            if user_input.lower() == 'q':
                ask_again = input("Are you sure? Exit the game? (yes or no) ")
                if ask_again in ["y", "yes"]:
                    print("Exiting the game...")
                    time.sleep(0.5)
                    quit()
                elif ask_again in ["no", "n"]:
                    print("Continue the game..")
                    continue
                else:
                    print("Invalid input! Continue the game..")
                    continue

            try:
                ask_for_guess = int(user_input)
            except ValueError:
                print("Enter integer as an input and try again")
                continue

            # checking the guess range
            if ask_for_guess not in range(1, 101):
                print("Your guess is out of range, try again!!")
                continue

            prev_guess.append(ask_for_guess)
            print(f"Previous Guesses: {prev_guess}")

            if ask_for_guess > target_number:
                print(f"{ask_for_guess} is higher than the guess.")
            elif ask_for_guess < target_number:
                print(f"{ask_for_guess} is lower than the guess.")
            else:
                print(f"{ask_for_guess} is correct guess!")
                break

            tries -= 1
            if tries > 0:
                print(f"{tries} left.")
            else:
                print(f"Tries left: {tries}. You ran out of all tries")
                print(f"The correct guess was: {target_number}")


        another_guess = input("Want to go another round? (yes or no?): ").lower().strip()
        if another_guess in ["yes", "y"]:
            print("Starting next round...")
            time.sleep(0.5)
        else:
            print("Exiting...")
            time.sleep(1)
            print("Exited!")
            quit()

if __name__ == "__main__":
    number_guessing_game()
